import os
import streamlit as st
from dotenv import load_dotenv
from langchain_pinecone import PineconeVectorStore
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI

# --- 1. LOAD ENVIRONMENT VARIABLES ---
load_dotenv()

if not os.getenv("GOOGLE_API_KEY") or not os.getenv("PINECONE_API_KEY"):
    st.error("Missing API keys! Please check your .env file.")
    st.stop()

# --- 2. SET UP STREAMLIT UI ---
st.set_page_config(page_title="Sports AI Expert", page_icon="🏅")
st.title("Global Sports RAG Chatbot")
st.caption("Ask me about 100 different sports!")

# --- 3. INITIALIZE AI COMPONENTS (Cached for speed) ---
@st.cache_resource
def initialize_rag_pipeline():
    # A. Connect to the Embeddings & Pinecone Index
    embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")
    index_name = "sports-rag-index" # Must match what you used in the upload script
    
    vectorstore = PineconeVectorStore(
        index_name=index_name, 
        embedding=embeddings
    )
    
    # Configure the retriever to fetch the top 3 most relevant sports chunks
    retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

    # B. Initialize Gemini 1.5 Flash with Streaming enabled
    llm = ChatGoogleGenerativeAI(
        model="gemini-flash-latest",
        temperature=0.3, # Low temperature keeps it factual and grounded
        streaming=True
    )
    
    return retriever, llm

retriever, llm = initialize_rag_pipeline()

# --- 4. MANAGE CHAT HISTORY ---
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "Hi! I'm your sports encyclopedia. Ask me about the rules, origins, or famous countries of any sport!"}
    ]

# Display previous messages on app rerun
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# --- 5. HANDLE USER INPUT & STREAM RESPONSE ---
if user_query := st.chat_input("E.g., 'What are the rules of Cricket?' or 'Tell me about Surfing.'"):
    
    # Add user message to UI and history
    st.session_state.messages.append({"role": "user", "content": user_query})
    with st.chat_message("user"):
        st.markdown(user_query)

    # Generate the assistant's response
    with st.chat_message("assistant"):
        # 1. Retrieve the relevant context from Pinecone
        retrieved_docs = retriever.invoke(user_query)
        context = "\n\n".join([doc.page_content for doc in retrieved_docs])
        
        # 2. Construct the strict RAG prompt
        rag_prompt = f"""You are a helpful sports expert. Use ONLY the following pieces of retrieved context to answer the user's question. 
        If the answer is not contained in the context, do not guess. Simply say, "I'm sorry, but I don't have that information in my sports knowledge base."
        
        Context:
        {context}
        
        User Question: {user_query}
        
        Answer:"""
        
       # 3. Stream the response from Gemini Flash
        message_placeholder = st.empty()
        full_response = ""
        
        # .stream() returns chunks as they are generated by the model
        for chunk in llm.stream(rag_prompt):
            
            # Hyper-safe extraction: handle strings, populated lists, and empty chunks
            if isinstance(chunk.content, list) and len(chunk.content) > 0:
                chunk_text = chunk.content[0].get("text", "")
            elif isinstance(chunk.content, str):
                chunk_text = chunk.content
            else:
                chunk_text = "" # Catch-all for empty metadata chunks
                
            full_response += chunk_text
            
            # Add a blinking cursor to simulate typing
            message_placeholder.markdown(full_response + "▌")
            
        # Clear the cursor and show final output
        message_placeholder.markdown(full_response)
        
    # Save the assistant's response to history
    st.session_state.messages.append({"role": "assistant", "content": full_response})