from fpdf import FPDF

sports_data = [
    {"name": "1. Soccer (Football)", "origin": "England", "players": "11 per team", "rules": "No hands allowed except for the goalkeeper inside the penalty area. The offside rule prevents attacking players from lingering behind the last defender. Matches last 90 minutes across two halves. Fouls can result in direct/indirect free kicks, penalties, or yellow/red cards.", "countries": "Brazil, Germany, Argentina, France"},
    {"name": "2. Basketball", "origin": "USA", "players": "5 per team", "rules": "Players must dribble to move with the ball; stopping and walking is a 'traveling' violation. Teams have a 24-second shot clock to hit the rim. Scoring inside the arc is 2 points, outside is 3 points, and free throws are 1 point. A player is ejected after 5 or 6 personal fouls.", "countries": "USA, Spain, France, Serbia"},
    {"name": "3. Cricket", "origin": "England", "players": "11 per team", "rules": "A bowler delivers a hard ball to a batsman; runs are scored by running between wickets or hitting boundaries (4 runs if it bounces, 6 if it clears the rope). Ten batsmen must be dismissed to end an innings. Dismissals include bowled, caught, LBW (Leg Before Wicket), and run out.", "countries": "India, Australia, England, Pakistan"},
    {"name": "4. Tennis", "origin": "France/England", "players": "1 or 2 per team", "rules": "The ball must bounce once or be hit out of the air over the net into the marked boundaries. Serving must be done diagonally into the service box. Scoring follows a 15, 30, 40 sequence. 'Deuce' occurs at 40-40, requiring a two-point lead to win the game.", "countries": "Spain, Switzerland, Serbia, USA"},
    {"name": "5. Volleyball", "origin": "USA", "players": "6 per team", "rules": "A team has a maximum of 3 hits to return the ball over the net. The ball must not hit the floor in bounds. Players rotate positions clockwise after winning the serve. Touching the net or stepping over the centerline is a fault.", "countries": "Brazil, Italy, Poland, USA"},
    {"name": "6. Rugby Union", "origin": "England", "players": "15 per team", "rules": "The ball can only be passed backwards or sideways, never forwards. Tackles are only allowed on the ball carrier below the shoulders. A 'try' is scored by grounding the ball in the opponent's in-goal area (5 points), followed by a conversion kick (2 points).", "countries": "New Zealand, South Africa, England"},
    {"name": "7. Baseball", "origin": "USA", "players": "9 per team", "rules": "A batter gets three strikes for an out, or four balls for a free walk to first base. Games consist of 9 innings. Runs are scored by advancing counter-clockwise around four bases. A ball hit over the outfield wall in fair territory is a home run.", "countries": "USA, Japan, Dominican Republic, Cuba"},
    {"name": "8. Golf", "origin": "Scotland", "players": "Individual", "rules": "The objective is to hit the ball into a hole in the fewest strokes possible across an 18-hole course. If a ball goes out of bounds or into a water hazard, penalty strokes are added. Players must play the ball as it lies without moving it.", "countries": "USA, Scotland, Northern Ireland, Australia"},
    {"name": "9. Table Tennis", "origin": "England", "players": "1 or 2 per team", "rules": "The serve must bounce on the server's side first, then the opponent's. In doubles, serves must be diagonal. Matches are usually best of 5 or 7 games, played to 11 points, and must be won by a margin of 2 points. Let serves are replayed.", "countries": "China, Japan, Germany, South Korea"},
    {"name": "10. Badminton", "origin": "India/England", "players": "1 or 2 per team", "rules": "The shuttlecock must not hit the ground. Serves must be hit underhand and land in the diagonally opposite service box. Games are played to 21 points; if tied at 20-20, a 2-point lead is required, capped at a maximum of 30 points.", "countries": "China, Indonesia, Denmark, Malaysia"},
    {"name": "11. Field Hockey", "origin": "England", "players": "11 per team", "rules": "Players can only hit the ball with the flat side of their stick. The ball cannot touch a player's feet or body. Goals can only be scored from inside the striking circle. Obstructing an opponent from playing the ball is a foul.", "countries": "Netherlands, Australia, India, Belgium"},
    {"name": "12. Athletics (Track & Field)", "origin": "Ancient Greece", "players": "Individual/Relay", "rules": "Sprinting events require runners to stay in their designated lanes; false starts result in disqualification. Jumping/throwing events have designated fault lines. Relay races require a baton pass within a specific 20-meter zone.", "countries": "USA, Jamaica, Kenya, Great Britain"},
    {"name": "13. Boxing", "origin": "Ancient Greece/UK", "players": "1v1", "rules": "Punches are only allowed above the belt with padded gloves. Holding, tripping, and hitting the back of the head are fouls. Scored on a 10-point must system by judges. A bout ends via Knockout (KO), Technical Knockout (TKO), or judge decision.", "countries": "USA, Mexico, UK, Ukraine"},
    {"name": "14. Mixed Martial Arts (MMA)", "origin": "Brazil/USA", "players": "1v1", "rules": "Combines striking and grappling. Illegal moves include eye-gouging, groin strikes, 12-to-6 downward elbows, and kicking a grounded opponent in the head. Bouts are usually 3 or 5 rounds of 5 minutes. Wins are by submission, KO, or decision.", "countries": "USA, Brazil, Russia, Mexico"},
    {"name": "15. Swimming", "origin": "Ancient Egypt/Greece", "players": "Individual/Relay", "rules": "Swimmers must touch the wall on every turn and finish. Specific technical rules apply to Breaststroke (frog kick), Butterfly (dolphin kick), and Backstroke (must stay on back). False starts lead to immediate disqualification.", "countries": "USA, Australia, China, Great Britain"},
    {"name": "16. Gymnastics", "origin": "Ancient Greece", "players": "Individual/Team", "rules": "Routines are judged on a combined score of Difficulty (D-score) and Execution (E-score). Stepping out of bounds, falling off apparatuses, or missing required elements results in severe point deductions.", "countries": "USA, China, Russia, Japan"},
    {"name": "17. Cycling (Road)", "origin": "France", "players": "Individual/Team", "rules": "Riders race on paved roads. 'Drafting' (riding close behind someone to save energy) is crucial and allowed in road races, but strictly banned in individual Time Trials. Physical pushing or pulling of opponents is forbidden.", "countries": "France, Italy, Belgium, Colombia"},
    {"name": "18. Ice Hockey", "origin": "Canada", "players": "6 per team", "rules": "The game consists of three 20-minute periods. An 'offside' occurs if an attacking player enters the offensive zone before the puck. 'Icing' occurs when a team shoots the puck down the entire ice without it being touched. Penalties result in 2 to 5 minutes in the penalty box.", "countries": "Canada, USA, Russia, Sweden"},
    {"name": "19. American Football", "origin": "USA", "players": "11 per team", "rules": "The offense has 4 'downs' (plays) to gain 10 yards. A touchdown is worth 6 points, followed by a 1-point kick or 2-point play. Only one forward pass is allowed per play from behind the line of scrimmage. Blocking in the back is a penalty.", "countries": "USA"},
    {"name": "20. Wrestling", "origin": "Ancient Greece", "players": "1v1", "rules": "The ultimate goal is to pin both of the opponent's shoulders to the mat simultaneously. If no pin occurs, points are awarded for takedowns, escapes, reversals, and near-falls. Striking, biting, and joint locks are illegal.", "countries": "Russia, USA, Iran, Japan"},
    {"name": "21. Snooker", "origin": "India/UK", "players": "1v1", "rules": "Players must pot a red ball (1 point) followed by a color ball (2-7 points) in sequence. When all reds are gone, colors must be potted in ascending value order. Fouls (like potting the white cue ball) give 4 to 7 penalty points to the opponent.", "countries": "UK, China, Australia"},
    {"name": "22. Surfing", "origin": "Polynesia", "players": "Individual", "rules": "Surfers are scored on wave selection, size, and the difficulty of maneuvers performed. Priority rules govern who has the right of way on a wave; interfering with a surfer who has priority ('dropping in') results in a heavy score penalty.", "countries": "USA (Hawaii), Australia, Brazil"},
    {"name": "23. Fencing", "origin": "Spain/France", "players": "1v1", "rules": "Competitors use a Foil, Épée, or Sabre. In Foil and Sabre, 'right-of-way' rules dictate who gets the point if both hit simultaneously. Points are scored by making valid electronic contact with the weapon tip (or blade in Sabre) on the opponent's target area.", "countries": "Italy, France, Hungary, Russia"},
    {"name": "24. Archery", "origin": "Prehistoric", "players": "Individual/Team", "rules": "Archers shoot arrows at a 122cm target from 70 meters away (in standard Olympic recurve). The target has 10 concentric scoring rings; the inner gold ring scores 10. Ties are broken by a single-arrow shoot-off closest to the center.", "countries": "South Korea, USA, Italy"},
    {"name": "25. Alpine Skiing", "origin": "Europe (Alps)", "players": "Individual", "rules": "Skiers race against the clock down a snow-covered mountain. They must pass through a series of alternating red and blue gates. Missing a gate (straddling) results in immediate disqualification.", "countries": "Austria, Switzerland, USA"},
    {"name": "26. Snowboarding", "origin": "USA", "players": "Individual", "rules": "In freestyle events (Halfpipe, Slopestyle), judges score on trick amplitude, execution, difficulty, and variety. In racing events (Snowboard Cross), riders race simultaneously on a track with jumps and berms; intentional physical interference is penalized.", "countries": "USA, Canada, Japan"},
    {"name": "27. Water Polo", "origin": "Scotland/England", "players": "7 per team", "rules": "Players must tread water (eggbeater kick) and cannot touch the pool bottom. Only the goalkeeper can touch the ball with two hands. Teams have a 30-second shot clock. Excessive physical fouls lead to 20-second ejections.", "countries": "Hungary, Serbia, Italy, USA"},
    {"name": "28. Handball", "origin": "Denmark/Germany", "players": "7 per team", "rules": "Players can run three steps with the ball or hold it for three seconds before dribbling or passing. Goals must be scored from outside the 6-meter goal crease. Defensive players can use their body to block but cannot push or hit.", "countries": "Denmark, France, Germany, Spain"},
    {"name": "29. Taekwondo", "origin": "South Korea", "players": "1v1", "rules": "Primarily a kicking martial art. Electronic sensors on the chest guard and helmet register points. Kicks to the head score higher than punches to the body. Spinning kicks earn bonus points. Stepping out of the ring or falling incurs a penalty.", "countries": "South Korea, Iran, Great Britain"},
    {"name": "30. Judo", "origin": "Japan", "players": "1v1", "rules": "An 'Ippon' (instant win) is achieved by throwing an opponent flat on their back with force, holding them down for 20 seconds, or forcing a submission via choke or armlock. Stalling or refusing to grip the opponent results in 'Shido' (penalty).", "countries": "Japan, France, Georgia"},
    {"name": "31. Karate", "origin": "Japan (Okinawa)", "players": "1v1", "rules": "In Kumite (sparring), points (Yuko, Waza-ari, Ippon) are awarded for clean, controlled strikes to designated target areas. Strikes must show good form and awareness. Excessive contact or malicious strikes result in penalties or disqualification.", "countries": "Japan, France, Iran"},
    {"name": "32. Weightlifting", "origin": "Ancient Greece", "players": "Individual", "rules": "Athletes compete in two lifts: the Snatch (one continuous motion), and the Clean and Jerk (two motions). They get three attempts per lift. A 'press out' (bending and re-extending the elbows) invalidates the lift. Highest combined total wins.", "countries": "China, Georgia, Bulgaria"},
    {"name": "33. Rowing", "origin": "Ancient Egypt", "players": "1, 2, 4, or 8", "rules": "Boats race over a straight 2000m course. They must remain in their designated buoyed lanes; interfering with another boat's water results in disqualification. In 'sweep' rowing each holds one oar; in 'sculling' each holds two.", "countries": "Great Britain, New Zealand, Germany"},
    {"name": "34. Sailing", "origin": "Netherlands", "players": "Varies by boat", "rules": "Boats race around a marked course. Right-of-way rules are strict: port tack gives way to starboard tack, and windward gives way to leeward. Touching a mark (buoy) requires a penalty turn (360 degrees) to clear.", "countries": "Great Britain, Australia, New Zealand"},
    {"name": "35. Equestrian", "origin": "Ancient Greece", "players": "Individual/Team", "rules": "Includes Dressage, Show Jumping, and Eventing. In Jumping, knocking down a rail or refusing a jump incurs penalty faults. In Dressage, horse and rider are scored on the precision and grace of a memorized sequence of movements.", "countries": "Germany, Great Britain, USA"},
    {"name": "36. Squash", "origin": "England", "players": "1v1", "rules": "Players hit a small hollow rubber ball against the front wall. The ball can hit side walls but must hit the front wall above the tin and below the out line. A player wins a rally if the opponent lets the ball bounce twice or hits it out.", "countries": "Egypt, England, Pakistan"},
    {"name": "37. Racquetball", "origin": "USA", "players": "1v1", "rules": "Similar to squash, but the ball is larger and the court is longer with no tin. The ball can hit any surface (walls, ceiling) but must hit the front wall before bouncing on the floor. Serves must land beyond the short line.", "countries": "USA, Mexico, Canada"},
    {"name": "38. Lacrosse", "origin": "Indigenous North America", "players": "10 per team", "rules": "Players use sticks with netted pockets to pass and catch a hard rubber ball. The ball is advanced by running or passing. In the men's game, body checking and stick checking are legal; the women's game prohibits body checking.", "countries": "USA, Canada, Iroquois Nationals"},
    {"name": "39. Polo", "origin": "Ancient Persia", "players": "4 per team", "rules": "Played on horseback on a massive grass field. Players use mallets to hit a ball into goals. The 'line of the ball' creates a right-of-way to prevent dangerous collisions; crossing it unsafely is a foul. Play is divided into 'chukkers' (periods).", "countries": "Argentina, UK, USA"},
    {"name": "40. Netball", "origin": "England", "players": "7 per team", "rules": "Similar to basketball, but players cannot run or dribble with the ball; they must stop and pass within 3 seconds. The court is divided into thirds, and players are strictly restricted to certain zones based on their position.", "countries": "Australia, New Zealand, England"},
    {"name": "41. Darts", "origin": "England", "players": "1v1", "rules": "Players start with a score of 501 and subtract the points they hit on the dartboard. The outer thin ring is double points, the inner is triple. To win a game (leg), a player must reach exactly zero by hitting a 'double' on their final throw.", "countries": "England, Netherlands, Scotland"},
    {"name": "42. Bowling", "origin": "Ancient Egypt/Germany", "players": "Individual/Team", "rules": "A player rolls a heavy ball down a wooden/synthetic lane to knock down 10 pins. A game consists of 10 frames, with two throws per frame. A strike knocks down all pins on the first throw; a spare on the second. Crossing the foul line results in a zero score.", "countries": "USA, South Korea, Sweden"},
    {"name": "43. Figure Skating", "origin": "Europe", "players": "1 or 2", "rules": "Skaters perform a Short Program and a Free Skate. They are judged via the International Judging System (IJS) which awards base values for specific jumps (e.g., Axel, Lutz) and spins, plus Grades of Execution (GOE). Falls result in strict point deductions.", "countries": "Russia, USA, Japan, Canada"},
    {"name": "44. Bobsleigh", "origin": "Switzerland", "players": "2 or 4 per team", "rules": "Teams sprint to push a sled down an ice track, then jump in. The driver steers using rings connected to the front runners; the brakeman stops the sled after the finish line. The winner is determined by the lowest combined time over four heats.", "countries": "Germany, Switzerland, USA"},
    {"name": "45. Curling", "origin": "Scotland", "players": "4 per team", "rules": "Players slide heavy granite stones across a sheet of ice toward a target ('house'). Two sweepers use brooms to melt the ice friction, extending the stone's glide and altering its curl. The team with stones closest to the center scores points.", "countries": "Canada, Sweden, Scotland"},
    {"name": "46. Skateboarding", "origin": "USA", "players": "Individual", "rules": "Split into Street (stairs, handrails) and Park (bowls, transitions) disciplines. Skaters perform timed runs and individual trick attempts. Judges score based on trick difficulty, speed, amplitude, and flawless execution without falling (bailing).", "countries": "USA, Brazil, Japan"},
    {"name": "47. Sport Climbing", "origin": "USSR/Europe", "players": "Individual", "rules": "Disciplines include Bouldering (short, ropeless complex routes), Lead (climbing high with a rope, clipping in), and Speed (racing side-by-side up a standardized wall). Touching the ground or pulling on quickdraws results in a failed attempt.", "countries": "Slovenia, Japan, USA"},
    {"name": "48. Triathlon", "origin": "USA", "players": "Individual", "rules": "A continuous race of Swimming, Cycling, and Running. Time spent transitioning between sports (T1 and T2) counts toward the total time. Drafting is illegal in standard Ironman distances but allowed in Olympic draft-legal races.", "countries": "Great Britain, USA, Australia"},
    {"name": "49. Kabaddi", "origin": "India", "players": "7 per team", "rules": "A 'raider' runs into the opposing half to tag defenders and return safely, all while chanting 'Kabaddi' in a single breath. Defenders attempt to tackle the raider before they cross back. Tagged players are temporarily out.", "countries": "India, Iran, Pakistan"},
    {"name": "50. Sepak Takraw", "origin": "Southeast Asia", "players": "3 per team", "rules": "Often called 'kick volleyball.' Players use feet, knees, chest, and head to hit a rattan or synthetic ball over a net. Hands and arms are strictly forbidden. The game is highly acrobatic, featuring mid-air bicycle kick spikes.", "countries": "Thailand, Malaysia, Indonesia"},
    {"name": "51. Ultimate Frisbee", "origin": "USA", "players": "7 per team", "rules": "Players cannot run with the disc; they must pivot and pass. A point is scored by catching the disc in the opponent's endzone. If a pass is dropped, intercepted, or goes out of bounds, it is an immediate turnover. The sport is self-officiated.", "countries": "USA, Canada, Japan, Australia"},
    {"name": "52. Padel", "origin": "Mexico", "players": "2 per team (Doubles)", "rules": "Played on an enclosed court smaller than a tennis court. Serves must be underhand. The ball can bounce off the glass walls after hitting the floor. Scoring is identical to tennis (15, 30, 40, Game).", "countries": "Spain, Argentina, Sweden, Mexico"},
    {"name": "53. Pickleball", "origin": "USA", "players": "1 or 2 per team", "rules": "Played with a paddle and a perforated plastic ball. The serve must be underhand. The 'two-bounce rule' dictates the ball must bounce once on the serve and once on the return. Players cannot volley the ball while standing in the 'kitchen' (non-volley zone).", "countries": "USA, Canada, UK, Australia"},
    {"name": "54. Water Skiing", "origin": "USA", "players": "Individual", "rules": "Skier is pulled behind a boat. Slalom events require the skier to navigate around 6 alternating buoys while the boat rope gets progressively shorter. Jump events are judged on distance. Trick events are scored on maneuvers over 20 seconds.", "countries": "USA, Australia, France, Canada"},
    {"name": "55. Wakeboarding", "origin": "USA", "players": "Individual", "rules": "Riders are towed behind a boat and use the boat's wake to launch into the air to perform flips and spins. Judges score runs based on execution, intensity, and variety of tricks. A fall results in lost points.", "countries": "USA, Australia, Great Britain, Germany"},
    {"name": "56. Kitesurfing", "origin": "France", "players": "Individual", "rules": "Riders use a large power kite to harness the wind and ride on a board over water. Freestyle events judge aerial tricks and height; racing events (kite foil) follow standard sailing regatta course rules.", "countries": "France, Brazil, USA, Netherlands"},
    {"name": "57. Windsurfing", "origin": "USA", "players": "Individual", "rules": "Combines elements of surfing and sailing on a board with an attached sail. Olympic iQFoil racing requires navigating a course. Rules mirror sailing right-of-way protocols to prevent collisions. Pumping the sail excessively is restricted in some classes.", "countries": "Netherlands, France, Israel, Great Britain"},
    {"name": "58. Paragliding", "origin": "France", "players": "Individual", "rules": "Pilots fly lightweight, free-flying, foot-launched glider aircraft. Cross-country competitions involve racing around a pre-defined course using thermal updrafts. Entering restricted airspace or flying dangerously close to others causes disqualification.", "countries": "France, Switzerland, Austria, Germany"},
    {"name": "59. Skydiving", "origin": "France/USA", "players": "Individual/Team", "rules": "Competitive disciplines include Formation Skydiving, where teams build geometric formations in freefall against a clock, and Canopy Piloting (swooping), judged on speed, distance, and accuracy over water.", "countries": "USA, France, Russia, UAE"},
    {"name": "60. Motocross", "origin": "UK", "players": "Individual", "rules": "Off-road motorcycle racing held on enclosed dirt circuits with jumps and sharp turns. Races usually begin with a mass start from a starting gate. Cutting the track or receiving outside assistance results in penalties or disqualification.", "countries": "USA, France, Belgium, Netherlands"},
    {"name": "61. Formula 1", "origin": "Europe", "players": "Individual/Team", "rules": "Open-wheel cars race on closed circuits. Qualifying determines grid position. Drivers must use at least two different tire compounds during a dry race. Forcing another driver off the track or ignoring flag signals incurs time penalties.", "countries": "Great Britain, Italy, Germany, Brazil"},
    {"name": "62. Rally Racing", "origin": "Monaco/France", "players": "2 per car (Driver/Co-driver)", "rules": "Cars race against the clock on closed public roads (tarmac, gravel, snow). The co-driver reads pace notes describing the road ahead. The lowest cumulative time across multiple stages wins. Late arrival at a checkpoint incurs time penalties.", "countries": "Finland, France, UK, Sweden"},
    {"name": "63. NASCAR", "origin": "USA", "players": "Individual/Team", "rules": "Stock car racing primarily on oval tracks. Cars must meet strict templates for weight, engine size, and aerodynamics. Pit road speed limits are strictly enforced. Intentionally causing a wreck under caution flags leads to severe point docks.", "countries": "USA"},
    {"name": "64. MotoGP", "origin": "Europe", "players": "Individual/Team", "rules": "The premier class of motorcycle road racing on purpose-built prototypes. Jump starts result in ride-through or long-lap penalties. Exceeding track limits repeatedly results in time penalties. Riders must yield to faster qualifying laps in practice.", "countries": "Spain, Italy, Australia, France"},
    {"name": "65. Karting", "origin": "USA", "players": "Individual", "rules": "Open-wheel motorsport using small, four-wheeled vehicles. Often the stepping stone to F1. Intentional ramming, blocking, or gaining an advantage by leaving the track limits results in a black flag (disqualification) or time penalty.", "countries": "Italy, Great Britain, Finland, USA"},
    {"name": "66. BMX Racing", "origin": "USA", "players": "Individual", "rules": "Bicycle motocross sprint races on purpose-built single-lap dirt tracks. Eight riders launch from a starting gate. Intentional interference or swerving to block another rider unsafely can lead to relegation or disqualification.", "countries": "USA, Colombia, France, Netherlands"},
    {"name": "67. Mountain Biking (Downhill)", "origin": "USA", "players": "Individual", "rules": "Riders complete a single time-trial run down a steep, rough terrain track featuring jumps and rock gardens. Riders must pass between colored course tape/poles; cutting the course results in disqualification.", "countries": "Great Britain, France, USA, Canada"},
    {"name": "68. Track Cycling", "origin": "Great Britain", "players": "Individual/Team", "rules": "Held on steeply banked wooden velodromes. Events range from Sprints to the Keirin (following a motorized pacer) and Team Pursuit. Entering the sprinter's lane when occupied or failing to hold a straight line during a sprint is an infraction.", "countries": "Great Britain, Netherlands, Australia, Germany"},
    {"name": "69. Powerlifting", "origin": "USA/UK", "players": "Individual", "rules": "Athletes compete in three lifts: Squat, Bench Press, and Deadlift. In the squat, hips must drop below the knees. In the bench, the bar must pause motionless on the chest. In the deadlift, the lifter must lock out fully without 'hitching' the bar.", "countries": "USA, Russia, Ukraine, Great Britain"},
    {"name": "70. Bodybuilding", "origin": "Ancient Greece", "players": "Individual", "rules": "Competitors are judged solely on physical appearance: muscle size, symmetry, conditioning, and stage presentation (posing). Judges use a mandatory sequence of poses (e.g., front double bicep, lat spread). No athletic movements are performed.", "countries": "USA, UK, Egypt, Iran"},
    {"name": "71. Strongman", "origin": "Scotland/Iceland", "players": "Individual", "rules": "Events test absolute functional strength (e.g., lifting Atlas Stones, pulling trucks, carrying heavy yokes). Scoring is typically based on time to complete a task or maximum weight lifted. Straps are allowed, but deadlift suits are heavily regulated.", "countries": "Iceland, USA, Great Britain, Poland"},
    {"name": "72. Arm Wrestling", "origin": "Ancient Egypt", "players": "1v1", "rules": "Competitors lock hands over a table and attempt to pin the opponent's wrist to the touch pad. Elbows must remain on the elbow pad. A 'slip' results in the competitors being bound by a strap. Two fouls (e.g., false start, elbow lift) equal a loss.", "countries": "USA, Russia, Georgia, Canada"},
    {"name": "73. Tug of War", "origin": "Ancient Greece/China", "players": "8 per team", "rules": "Teams pull on opposite ends of a thick rope. The objective is to pull the rope so the mark crosses the center line. 'Locking' the rope around the body (except for the anchorman) or sitting on the ground for extended periods is a foul.", "countries": "Great Britain, Switzerland, Netherlands, Taiwan"},
    {"name": "74. Sumo Wrestling", "origin": "Japan", "players": "1v1", "rules": "A wrestler loses if any part of their body other than the soles of their feet touches the ground, or if they are forced outside the circular ring (dohyo). Hair pulling, eye poking, and striking with closed fists are strictly prohibited.", "countries": "Japan, Mongolia, Georgia, Hawaii(USA)"},
    {"name": "75. Muay Thai", "origin": "Thailand", "players": "1v1", "rules": "Known as the 'Art of Eight Limbs.' Fighters can strike with punches, kicks, elbows, and knees. Clinching (holding the opponent to strike or sweep) is allowed and heavily utilized. Matches are typically five 3-minute rounds.", "countries": "Thailand, France, Great Britain, Brazil"},
    {"name": "76. Kickboxing", "origin": "Japan/USA", "players": "1v1", "rules": "Combines boxing punches with martial arts kicks. Unlike Muay Thai, elbows are generally banned, and clinching is either prohibited or strictly limited to a few seconds. Fights end via KO, TKO, or judge's scorecards.", "countries": "Netherlands, Japan, USA, Morocco"},
    {"name": "77. Brazilian Jiu-Jitsu", "origin": "Brazil", "players": "1v1", "rules": "A grappling art focusing on ground fighting. Wins are achieved by forcing an opponent to 'tap out' via joint locks or chokeholds, or by accumulating points for positional dominance (mount, back control). Striking is completely banned.", "countries": "Brazil, USA, Japan, UAE"},
    {"name": "78. Sambo", "origin": "USSR (Russia)", "players": "1v1", "rules": "A martial art combining wrestling and judo. Sport Sambo focuses on throws and ground submissions (leg locks are allowed, but chokes are illegal). Combat Sambo allows punches, kicks, elbows, knees, and headbutts, resembling MMA in a jacket.", "countries": "Russia, Belarus, Georgia, Bulgaria"},
    {"name": "79. Krav Maga", "origin": "Israel", "players": "N/A (Self-Defense)", "rules": "Not formally a competitive sport with rules, but a self-defense system. It focuses on real-world situations, encouraging extreme efficiency. Techniques involve attacking vulnerable areas (groin, eyes, throat) to neutralize threats immediately.", "countries": "Israel, USA, France, UK"},
    {"name": "80. Aikido", "origin": "Japan", "players": "1v1 (Demonstration)", "rules": "A non-competitive martial art. Practitioners (Aikidoka) use the momentum of an attacker against them via throws and joint locks. The goal is to defend oneself while protecting the attacker from injury. There are no tournaments or scoring.", "countries": "Japan, France, USA, Germany"},
    {"name": "81. Kendo", "origin": "Japan", "players": "1v1", "rules": "Japanese sword fencing using bamboo swords (shinai) and protective armor. Strikes must hit specific target areas (head, wrist, torso) while shouting the target's name (kiai). The first to score two points (Ippon) wins the match.", "countries": "Japan, South Korea, USA, France"},
    {"name": "82. Capoeira", "origin": "Brazil", "players": "1v1", "rules": "An Afro-Brazilian martial art combining elements of dance, acrobatics, and music. 'Played' in a circle (roda). Practitioners throw sweeping kicks and dodges in a fluid, rhythmic exchange without making heavy physical contact. There is no point scoring.", "countries": "Brazil, USA, France, Portugal"},
    {"name": "83. Wushu (Taolu)", "origin": "China", "players": "Individual", "rules": "A modern exhibition and full-contact sport derived from traditional Chinese martial arts. In Taolu (forms), athletes are judged on the speed, power, and flawless execution of choreographed routines, often using weapons like broadswords or spears.", "countries": "China, Iran, Macau, Vietnam"},
    {"name": "84. Tai Chi", "origin": "China", "players": "Individual", "rules": "Originally a martial art, now primarily practiced for health and meditation. When competed (Push Hands), the goal is to unbalance the opponent without using raw force, relying on leverage and yielding. Striking or wrestling throws are illegal.", "countries": "China, USA, Taiwan, UK"},
    {"name": "85. Parkour", "origin": "France", "players": "Individual", "rules": "Navigating from point A to B in a complex environment as efficiently as possible using jumping, vaulting, and climbing. In competition (Speed runs), the fastest time wins. In Freestyle, athletes are judged on trick difficulty and flow.", "countries": "France, UK, USA, Russia"},
    {"name": "86. Trampolining", "origin": "USA", "players": "Individual", "rules": "Gymnasts perform acrobatic routines consisting of 10 continuous jumps on a trampoline. Routines are judged on execution, difficulty, and 'Time of Flight' (how long the athlete stays in the air). Landing on the padding ends the routine.", "countries": "China, Canada, Great Britain, Belarus"},
    {"name": "87. Rhythmic Gymnastics", "origin": "USSR", "players": "Individual/Team", "rules": "Exclusively for women. Gymnasts perform routines on a floor mat using apparatuses: Hoop, Ball, Clubs, or Ribbon. Judged on body difficulties (leaps, balances), apparatus handling, and synchronization with music. Dropping an apparatus incurs a massive penalty.", "countries": "Russia, Bulgaria, Israel, Italy"},
    {"name": "88. Synchronized Swimming (Artistic Swimming)", "origin": "Great Britain/Canada", "players": "Duet/Team", "rules": "Swimmers perform synchronized, choreographed routines in the water. Judged on execution, artistic impression, and difficulty. Swimmers are heavily penalized if they touch the bottom of the pool to push off during a lift or routine.", "countries": "Russia, China, USA, Japan"},
    {"name": "89. Diving", "origin": "Great Britain", "players": "Individual/Synchro", "rules": "Athletes jump from springboards (3m) or platforms (10m). Judged on the approach, takeoff, execution of mid-air twists/somersaults, and the entry (which should create as little splash as possible, known as a 'rip entry').", "countries": "China, Great Britain, USA, Mexico"},
    {"name": "90. Canoe Slalom", "origin": "Switzerland", "players": "Individual", "rules": "Paddlers race a timed course through roaring whitewater rapids. They must navigate through a series of hanging gates (green for downstream, red for upstream). Touching a gate adds a 2-second penalty; missing a gate adds 50 seconds.", "countries": "Slovakia, France, Germany, Czech Republic"},
    {"name": "91. Canoe Sprint", "origin": "Canada", "players": "1, 2, or 4 per boat", "rules": "Racing on flat water over straight distances (200m, 500m, 1000m). Paddlers must stay in their designated lanes. In a Canoe, the paddler kneels and uses a single-blade paddle. In a Kayak, they sit and use a double-blade paddle.", "countries": "Hungary, Germany, New Zealand, Spain"},
    {"name": "92. Stand Up Paddleboarding (SUP)", "origin": "USA (Hawaii)", "players": "Individual", "rules": "Riders stand on a large buoyant board and use a single-blade paddle. In racing events, the rules mirror canoe sprint or surf racing. Drafting behind another paddler is allowed in some formats. Falling off requires remounting without outside help.", "countries": "USA, Australia, France, Spain"},
    {"name": "93. Dragon Boat Racing", "origin": "China", "players": "22 per boat", "rules": "A team consists of 20 paddlers facing forward, one drummer at the bow to keep the rhythm, and a steerer at the stern. Races are sprints over flat water. All paddlers must stroke in unison to the drumbeat. Crossing lanes is an instant disqualification.", "countries": "China, Canada, Germany, Philippines"},
    {"name": "94. Water Aerobics", "origin": "USA", "players": "Group", "rules": "A non-competitive fitness activity involving cardiovascular and resistance training in shallow water. There are no rules, but the water provides natural resistance while reducing impact on joints compared to land-based aerobics.", "countries": "USA, UK, Australia, Canada"},
    {"name": "95. Modern Pentathlon", "origin": "Ancient Greece / Modern Europe", "players": "Individual", "rules": "Combines five events: Fencing (1-touch épée), Freestyle Swimming (200m), Equestrian Show Jumping (unfamiliar horse), and a combined Laser Pistol Shooting and Cross-Country Running event. Points from the first three events determine the starting staggered time for the final run.", "countries": "Great Britain, Hungary, Russia, South Korea"},
    {"name": "96. Bocce", "origin": "Italy", "players": "1, 2, or 4 per team", "rules": "Players throw heavy balls toward a smaller target ball called a 'pallino' on a long dirt or turf court. Points are awarded to the team with balls closest to the pallino after all balls are thrown. Hitting opponent balls away is a valid strategy.", "countries": "Italy, France, USA, Argentina"},
    {"name": "97. Pétanque", "origin": "France", "players": "1, 2, or 3 per team", "rules": "Similar to Bocce, but played with hollow metal balls. The thrower must stand with both feet together inside a small starting circle. The goal is to toss the metal balls as close as possible to the wooden target ball (the 'cochonnet').", "countries": "France, Madagascar, Belgium, Thailand"},
    {"name": "98. Horseshoe Pitching", "origin": "Ancient Rome", "players": "1v1 or 2v2", "rules": "Players toss U-shaped metal horseshoes at a stake in the ground 40 feet away. A 'ringer' (encircling the stake) is worth 3 points; a horseshoe landing within 6 inches of the stake is 1 point. Opponent scores can cancel each other out.", "countries": "USA, Canada"},
    {"name": "99. Croquet", "origin": "England", "players": "1v1 or 2v2", "rules": "Players use mallets to hit wooden/plastic balls through a sequence of wire hoops embedded in a grass lawn. Hitting an opponent's ball allows you to 'roquet' it, granting extra shots and the ability to knock their ball out of position.", "countries": "England, New Zealand, USA, Australia"},
    {"name": "100. Billiards (Carom)", "origin": "France", "players": "1v1", "rules": "Played on a pocketless table with three balls. In the popular 'Three-Cushion' variant, a player must strike their cue ball so that it hits both the other two balls, but it must also hit at least three rail cushions before striking the final ball to score a point.", "countries": "South Korea, Belgium, Turkey, Netherlands"}
]

pdf = FPDF()

pdf.add_page()
pdf.set_auto_page_break(auto=True, margin=15)

for sport in sports_data:
    # Sport Name (Heading)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, sport['name'], ln=1)
    
    # Details
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 6, f"Origin Country: {sport['origin']}")
    pdf.multi_cell(0, 6, f"Number of Players: {sport['players']}")
    pdf.multi_cell(0, 6, f"Important Rules: {sport['rules']}")
    pdf.multi_cell(0, 6, f"Famous Countries: {sport['countries']}")
    
    pdf.ln(4) # Space between sports
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y()) # separator line
    pdf.ln(4)

pdf.output('sports_encyclopedia.pdf')
print("Successfully created 'sports_encyclopedia.pdf'")